name: Lints

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Check formatting
        run: cargo make fmt-check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Clippy
        run: cargo make clippy
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustc nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-docs
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
      - name: Doc
        run: cargo make doc
